# fly.toml app configuration file generated for fastfolder on 2025-09-10T13:48:17-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastfolder'
primary_region = 'sjc'
swap_size_mb = 1024

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ENVIRONMENT = "production"
  UPLOAD_DIR = "/data/uploads"
  DATABASE_URL = "sqlite+aiosqlite:///./data/test.db"

[[mounts]]
  source = "data"
  destination = "/data"
