site_name: Learning Documentation
site_description: Learning materials for the conversation management system
site_url: https://example.com/learning

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - AI Chat UI: ai_chat_ui.md
  - Conversation Organization: conversation_organization.md
  - Vector DB & Hybrid Search: vector_db_hybrid_search.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
